# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('id_agua', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('hora', models.TimeField(verbose_name='hora')),
                ('valor', models.FloatField(verbose_name='valor')),
                ('unidad', models.CharField(max_length=3, verbose_name='unidad fisica')),
                ('estado', models.CharField(max_length=24, verbose_name='estado del transductor')),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id_criadero', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=255, verbose_name='Denominacion comercial del Criadero Av\xedcola')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa propietaria del establecimiento')),
                ('clave', models.CharField(max_length=255, verbose_name='Clave Fiscal')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id_logs', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Luz',
            fields=[
                ('id_luz', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('hora', models.TimeField(verbose_name='hora')),
                ('valor', models.FloatField(verbose_name='valor')),
                ('unidad', models.CharField(max_length=3, verbose_name='unidad fisica')),
                ('estado', models.CharField(max_length=24, verbose_name='estado del transductor')),
                ('id_criadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id_temp', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('hora', models.TimeField(verbose_name='hora')),
                ('valor', models.FloatField(verbose_name='valor')),
                ('unidad', models.CharField(max_length=1, verbose_name='unidad fisica')),
                ('estado', models.CharField(max_length=24, verbose_name='estado del transductor')),
                ('id_criadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Establecimiento')),
            ],
        ),
        migrations.AddField(
            model_name='agua',
            name='id_criadero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Establecimiento'),
        ),
    ]
